<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="Microsoft.Extensions.Http.Polly" Version="10.0.10" />
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.10" />
		<PackageReference Include="Microsoft.Extensions.DependencyModel" Version="10.0.10" />
		<PackageReference Include="FreeSql.Provider.Sqlite" Version="3.5.311" />
		<PackageReference Include="FreeSql.Repository" Version="3.5.311" />
		<PackageReference Include="protobuf-net" Version="3.2.56" />
		<PackageReference Include="Google.Protobuf" Version="3.34.2" />
		<PackageReference Include="Grpc.Net.Client" Version="2.83.0" />
		<PackageReference Include="NLog" Version="6.1.4" />
		<PackageReference Include="NLog.Extensions.Logging" Version="6.1.4" />
		<PackageReference Include="NLog.Web.AspNetCore" Version="6.1.4" />
		<PackageReference Include="Nethereum.Hex" Version="6.1.0" />
		<PackageReference Include="Nethereum.HdWallet" Version="6.1.0" />
		<PackageReference Include="Nethereum.Contracts" Version="6.1.0" />
		<PackageReference Include="MediatR" Version="14.2.0" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="StowayNet.Extensions.DependencyInjection">
	    <HintPath>..\dll\StowayNet.Extensions.DependencyInjection.dll</HintPath>
	  </Reference>
	  <Reference Include="TronNet">
	    <HintPath>..\dll\TronNet.dll</HintPath>
	  </Reference>
	  <Reference Include="TronNet.ABI">
	    <HintPath>..\dll\TronNet.ABI.dll</HintPath>
	  </Reference>
	  <Reference Include="TronNet.Crypto">
	    <HintPath>..\dll\TronNet.Crypto.dll</HintPath>
	  </Reference>
	  <Reference Include="TronNet.Protocol">
	    <HintPath>..\dll\TronNet.Protocol.dll</HintPath>
	  </Reference>
	</ItemGroup>
	
</Project>
